### PR TITLE
Adding land-worker command

### PR DESCRIPTION
**Pull request by arwineap**

### CODE REVIEW

**Comment by chendrix** [comment]
Hey @arwineap what's your use case for wanting this in fly?

If you are using the BOSH release, the worker's drain script will automatically land the worker.

If you are using the binaries, the binaries have the `land-worker` and `retire-worker` commands. In general, we would expect that it's the responsibility of the worker to register/deregister/land itself, and not to be managed by an operator.

**Comment by arwineap** [comment]
@chendrix All this time finding references to land-worker, it had never occurred to me that it was actually on the concourse binary and not in fly   :)

In instances where my systems need to scale up workers, the process is relatively straight forward, but in the instance of systems being scaled back down we need a way to drain containers so that we can decommission workers without interrupting jobs and throwing them into an aborted state.

The `concourse land-worker` does provide a way to manage that, but it requires logging into ssh, then re-specifying the public / private key which adds extra challenges to scripting the landing / retiring of workers. From this perspective, fly was a much more attractive option because I already have patterns of connecting and using fly to manage concourse.

**Comment by chendrix** [comment]
I think the original intent is that you clearly already have something which is "logging into ssh", because you are running the worker binary somehow. The drain script which lands the worker is simply a sidecar process to the running worker binary, which has the same access to configuration/ssh keys/etc.

I'll leave this open so you can explore trying to do what you want to do using just the binaries, but I'll probably close it if there's not a particularly compelling case for it to be in fly after you've explored it.

**Comment by arwineap** [comment]
Can you add some color to help me understand the reasoning behind having prune-worker but not land-worker / retire-worker? Is it some sort of security barrier, forcing land/retire to live in a place where people are required to also input the ssh keys?

In the end, I think that land is still an open atc api endpoint, so it's not too much trouble to issue commands directly

**Comment by chendrix** [comment]
Pruning a worker is just a database level command, it just means "This has stalled, but it's actually just gone, so remove it". Pruning a worker doesn't effect anything really other than the UI.

Landing a worker/retiring a worker is effectful, it causes the ATC to stop scheduling workloads on that and to eventually disconnect. 

The rationale for keeping it in the worker binary is exactly what you mentioned re security.

**Comment by chendrix** [comment]
Hi there,

I'm going to close this PR now because of the rationale given above. Thanks again for submitting it, though, and thanks again for liking Concourse enough to contribute to it!

**Pull request closed without merging**
