### PR TITLE
Add `fly resources` command

### PR DESCRIPTION
**Pull request by edtan**
This adds the `fly resources` command requested in concourse/concourse#1149.

This PR is intended to go along with 2 other PRs:
concourse/atc#295
concourse/go-concourse#14

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@edtan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=250)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=250) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@edtan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=250)!

**Comment by edtan** [comment]
Here's some sample output from running the commands on my local machine.

```
$fly -t local resources
handle                                worker        container-type  resource-config-id  resource-type            
66e81732-4f2f-40e5-4f03-4235e3f81f9b  36c9b18120c9  check           8                   Used by parent resource 6
74789e88-8287-45ac-67d4-c53f59fc6a6a  36c9b18120c9  check           6                   bitbucket-build-status   
a96617ab-ba43-4709-502c-586267c0ff2c  36c9b18120c9  check           1                   git                      

$fly -t local resources --detailed
handle                                worker        container-type  resource-config-id  resource-type              pipeline  resource-name
66e81732-4f2f-40e5-4f03-4235e3f81f9b  36c9b18120c9  check           8                   Used by parent resource 6  test      build-status 
74789e88-8287-45ac-67d4-c53f59fc6a6a  36c9b18120c9  check           6                   bitbucket-build-status     none      none         
a96617ab-ba43-4709-502c-586267c0ff2c  36c9b18120c9  check           1                   git                        test      git-repo123  
a96617ab-ba43-4709-502c-586267c0ff2c  36c9b18120c9  check           1                   git                        test      git-repo     
a96617ab-ba43-4709-502c-586267c0ff2c  36c9b18120c9  check           1                   git                        test2     git-repo     
```

**Comment by vito** [comment]
Hey, thanks for submitting this and adding tests and everything! It looks great.

One problem though: we just started on https://github.com/concourse/concourse/issues/2386 which makes these resource check containers even more global, to the point where it doesn't even make sense to list them in `fly containers` because they won't belong to any team in particular.

I think once that issue is done we'll likely need to explore new ways to debug and expose information about resource checks, because hijacking won't be viable once the containers are global to the instance (for security reasons).

To that end, I actually like your approach in having this as a completely separate command. But given that we have #2386 in flight right now, it'll take me a while to review this (and the other PRs). I suspect that at least some of the information that this exposes will be affected by the internal restructuring. Hmm...

**Comment by edtan** [comment]
Sounds good!  I'll keep an eye out for #2386 would be happy to change this PR accordingly once that has been completed.

**Comment by vito** [comment]
@edtan Since we're probably gonna end up doing https://github.com/concourse/concourse/issues/2534 prior to merging this, I'm gonna close these 3 PRs out. Once https://github.com/concourse/concourse/issues/2386 and the code restructure is done this'll have to be a new PR anyway, submitted to the 'one big repo'. :slightly_smiling_face: 

Thanks!

**Pull request closed without merging**
