### PR TITLE
Add ability to specify target via environment variable

### PR DESCRIPTION
**Pull request by aeijdenberg**
This allows `fly` to be invoked as:

```bash
FLY_TARGET_PROPS='{"token":{ ...}}' fly pipelines
```

where `FLY_TARGET_PROPS` is a JSON `rc.TargetProps`.

See <https://github.com/concourse/concourse/issues/1559>.

### CODE REVIEW

**Comment by vito** [comment]
I think I agree with the intent of this, but I'm not a fan of the format - our `~/.flyrc` format should be considered ad-hoc and exposing the JSON structure up to the user (granted, in a very automation-intended workflow) doesn't seem wise, and is hard to justify outside of the context of your particular use case.

Here's an alternative proposal: we could add separate global flags (with very specific, long names) to specify everything you would need to specify in order to have a target defined. Then, `-t` is just shorthand for a saved set of these flags (at least in the mental model - the code path would be unaffected).

Something like:

```sh
fly --target-url https://ci.concourse.ci --target-token-type Bearer --target-token-value 'abcdef...'
```

And then your SSO approach could just specify the value for those flags automatically.

**Comment by aeijdenberg** [comment]
@vito that would likely work for us. My gut feeling is that there's a slight security advantage in setting at least the bearer token in an environment variable rather than a flag (this prevents creds being visible to `ps` commands etc), but it's probably not that significant in the scheme of things.

(we've been a bit distracted by other tasks, but expect to get back onto this side of things probably early in the new year)

**Comment by vito** [comment]
I'd be fine with allowing the token flag to also come from the env. That's
easy to do with the cli library we use (go-flags).

**Comment by vito** [comment]
@aeijdenberg Any update on this?

**Comment by vito** [comment]
Closing due to inactivity. Thanks though!

**Comment by pivotal-jwinters** [comment]
@aeijdenberg we're going to move forward with the format suggested by @vito. 

We've added a new issue to track this work https://github.com/concourse/fly/issues/234

**Pull request closed without merging**
