### PR TITLE
Output fly version when updating

### PR DESCRIPTION
**Pull request by kurtmc**
Fixes issue https://github.com/concourse/concourse/issues/1093

### CODE REVIEW

**Comment by vito** [comment]
thanks!

**Comment by mariash** [comment]
this test failed https://github.com/concourse/fly/blob/master/integration/sync_test.go#L124

**Comment by kurtmc** [comment]
@mariash Thanks, I can fix the test later today.

**Comment by kurtmc** [comment]
@mariash Created a new pull request https://github.com/concourse/fly/pull/172

**Pull request merged**
