### PR TITLE
[WIP] Error on unused variables.

### PR DESCRIPTION
**Pull request by jmcarp**
I'm not sure of the best interface here--maybe it would be better to warn on unused variables instead, or to error/warn if the user passes a flag like `--err-unused`. Anyway, I thought I'd submit this for discussion, then clean up and add tests once we figure out how / whether this feature should work.

cc @cnelson @jcscottiii

### CODE REVIEW

**Comment by chendrix** [comment]
Does this mean like if someone has `{{}}` syntax and they have not provided a value for that, then given the `--err-unused` flag it would exit 1?

I want to capture this use case, but considering we will be doing concourse/concourse#545 in the near future I don't want this work to become quickly obsolete, as we will have the idea of unbound variables that are later filled in by Vault/Credhub/etc.

Because of that, I'm going to close this, but hopefully we capture this when doing that story.

**Comment by jmcarp** [comment]
@chendrix: the idea is to error when users provide parameters that *aren't* used. There's a parallel feature request for bosh at https://github.com/cloudfoundry/bosh/issues/1568. I'm not sure how much 545 would change this feature--if a user passes in variables that isn't needed, we can still tell them so.

**Comment by chendrix** [comment]
I think we're talking about the same thing.

After we add credhub/vault. Having, e.g.

```
{{some-key}}
```

unresolved at `fly set-pipeline` time would still be totally valid. It means "hey, this is a variable which is currently unbound but can be populated via credhub/vault.

Am I misunderstanding you?

**Comment by chendrix** [comment]
Is this if someone does e.g. `fly e -isome-input-that-doesnt-exist=foo` then it would complain?

**Comment by jmcarp** [comment]
I think we're talking about different things 😄. Let's say I have a pipeline like this:

```yaml
# pipeline.yml
...
- name: repo
  type: git
  source:
    uri: {{git-url}}
    branch: {{git-branch}}
...
```

...and some secrets like this:

```yaml
# secrets.yml
git-url: https://github.com/jmcarp/repo
git-branch: master
git-path: lol-unused
```

...and I run `fly -t ci set-pipeline -p pipeline -c pipeline.yml -l secrets.yml --err-unused`, I want to see output like `variable "git-path" is unused, why did you set it lol`.

**Comment by chendrix** [comment]
oh interesting. I guess I never considered that you might want that because we have a giant `secrets.yml` for all of our secrets for all of our pipelines. Have you found a specific need for that functionality?

**Comment by jmcarp** [comment]
I was just reminded of this patch earlier today. My team was using a pipeline with aws credentials, but switched to instance profiles. So our secrets files didn't need those credentials anymore. We happened to remember to drop them from the secrets file this time, but if we hadn't, we would have had secrets living in a file on my laptop longer than necessary, and increased the risk of exposing them. It would have been useful to get warned about unnecessary secrets as soon as we set the pipeline here.

**Pull request closed without merging**
