### PR TITLE
Added ssl client auth support

### PR DESCRIPTION
**Pull request by farcaller**
This is a simple extension that allows fly to authorize against concourse ci servers that require client certificate validation.

Note that this doesn't change any auth mechanisms of concourse itself, it only adds client ssl as an optional layer to any other auth option.

Given that the server doesn't do any client auth out of the box, this option is useful where concourse runs behind a reverse proxy that does ssl termination (e.g. nginx that checks client certs).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@farcaller Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=150)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=150) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@farcaller Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=150)!

**Comment by jtarchie** [comment]
@farcaller, would you be able to provide tests and an example how to reproduce the issue?

**Comment by farcaller** [comment]
I'll take a look. Note that this PR doesn't really deal with Client SSL support on concourse web server side — expecting that SSL auth (if any) is done by forwarding proxy.

**Comment by jtarchie** [comment]
@farcaller, we are not going to accept this PR. If you feel this is still important, please open an issue so it can be discussed because mutual-TLS support is probably a wider net than just auth.

Thanks!

**Comment by farcaller** [comment]
Following up in https://github.com/concourse/concourse/issues/1438.

**Pull request closed without merging**
