### PR TITLE
--token can be passed to login for oauth login

### PR DESCRIPTION
**Pull request by XenoPhex**
Will still display prompt if there are multiple oauth providers or token is invalid.

### CODE REVIEW

**Comment by vito** [comment]
Might as well have it skip interaction entirely; if they're providing a token it really doesn't matter what auth methods are configured (you can even get one via basic auth).

**Comment by XenoPhex** [comment]
It's only prompted if there are 2+ oauth methods, otherwise it picks the first oauth.

If an invalid token is provided, it'll prompted again.

**Comment by vito** [comment]
Sure, but why prompt at all if the user's already providing a token? I'd expect that to just save it directly (possibly with format validation, which would just make it exit with an error). If you're passing `--token` it's unlikely that you're expecting interactivity (similar to `--username` and `--password` usage for scripts).

**Comment by XenoPhex** [comment]
Seems legit, I'll just make it hard error if it's not formatted correctly.

**Comment by vito** [comment]
Just gonna close this for now since it's gone a bit stagnant and we don't really need it.

**Pull request closed without merging**
