### PR TITLE
Fix typo in set-pipeline help text

### PR DESCRIPTION
**Pull request by jpluscplusm**
This PR fixes a typo.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jpluscplusm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=182)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=182) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jpluscplusm** [comment]
Please don't make me sign a CLA for this.

**Comment by jpluscplusm** [comment]
Please do a clean-room reimplementation of this without my offending IP. I can't sign a CLA right now ...

**Comment by jtarchie** [comment]
@jpluscplusm, we might be able to differ to [best judgement](https://cla.pivotal.io/about#obvious-fixes) here, so you don't have to sign the CLA.

**Comment by jtarchie** [comment]
@jpluscplusm, PR #180 was actually ahead of you. Thanks for the PR!

**Pull request closed without merging**
