### PR TITLE
Windows colours

### PR DESCRIPTION
**Pull request by alex-slynko**
Add colour output for Windows

### CODE REVIEW

**Comment by alex-slynko** [comment]
fixes #71

**Comment by pivotal-issuemaster** [comment]
@alex-slynko Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=127) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@alex-slynko Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=127)!

**Comment by vito** [comment]
thanks! the CI failure looks innocuous (we've got a dependency out of date), so I'll go ahead and merge this anyway

**Pull request merged**
