### PR TITLE
Added flag ` --non-interactive` to `fly set-team` and `destroy-team` #1326

### PR DESCRIPTION
**Pull request by aleksey-hariton**
… issue #1326

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@aleksey-hariton Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=191)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=191) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@aleksey-hariton Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=191)!

**Comment by SHyx0rmZ** [comment]
It would be great if you could run `go fmt` on the two files you modified, as this will unify the spacing and alignment in the structs and is considered best practice in the Go community.

**Comment by aleksey-hariton-epam** [comment]
@SHyx0rmZ I'll, first experience with Go :)

Also need to fix tests.

**Comment by aleksey-hariton-epam** [comment]
@SHyx0rmZ done

**Comment by jama-pivotal** [comment]
Thanks for the PR @aleksey-hariton-epam . I've scheduled it under our UX project as Ready to Work, someone from our team should be reviewing it soon!

**Pull request merged**
