### PR TITLE
Hijack by url

### PR DESCRIPTION
**Pull request by dsharp-pivotal**
This adds a feature to fly hijack to use a Concourse UI URL to help identify the container to connect to. It also checks that the target's URL and team match that in the passed URL.

### CODE REVIEW

**Comment by schubert** [comment]
Anyone on the team care to comment on whether this approach is acceptable or do we need to relook at this?

cc @vito

**Comment by chendrix** [comment]
I am personally a bit uneasy about accepting this as-is.

I think the fundamental desire is to make it easier to go from looking at a build in the UI to hijacking into a specific container.

However, your target's URL doesn't necessarily have to match a URL, as you could have different DNS records, or just be targeting the IP address, etc. 

Would an enhancement to the UI that printed out the arguments you need to pass to `fly -t <target> i ` be an acceptable alternative to this approach?

**Comment by dsharp-pivotal** [comment]
My understanding is that the UI used to show the build ID somewhere, and that could be passed to `fly -t <target> i -b <buildid>`. Restoring that would probably be an acceptable alternative.

It's true that the target doesn't strictly have to match the URL. But I think it's also true that if the target does match the URL, then the target is definitely the same target and is accessible. That is, if your browser can hit the URL, then so can fly. That also seems to be the simplest and most likely configuration for a fly target. ("How do I find the target URL?" "It's the same as the URL you use in your browser.")

**Comment by jimmyyih** [comment]
For whatever my opinion is worth, this "hijack by URL" feature has been very helpful in my developer workflow.  Would love to see this merged in some form.

**Comment by ashwinstar** [comment]
This is extremely useful to have +1, and have been using it extremely frequently on private fork since it became a think.

**Comment by dsharp-pivotal** [comment]
@chendrix  I thought of way that "hijack by url" is an improvement over "show the buildid in the UI" that I don't think I've articulated yet: Since the URL includes both the target host and team, a user is protected against specifying the wrong target, or if the target being logged in to the wrong team.

**Comment by professor** [comment]
I have been using the code in this pull request and have found it super helpful. 

Could the UI do something more helpful? Maybe. 

I just want to copy and paste one thing to be able to get into the container.

**Comment by bradfordboyle** [comment]
Echoing @professor, I have been using this code and it definitely reduces the friction in troubleshooting a failing job. I would also like to see this as an option for `fly watch` since searching/parsing through a failed jobs output in the browser is clunky compared to grepping from the terminal.

**Comment by tom-meyer** [comment]
The functionality that we've added here is quite useful to many teams in the Data org. We are eager to see this merged in, as running a branched version of Concourse with our special `fly` is a hassle.

Has there been any eyes on this? Is there anything we can change that will make it acceptable for merge? We're totally OK with doing more work on this if need be, to fix any issues you might see. Any forward progress (even short of a merge) would be great.

Thanks!

**Comment by akshaymankar** [comment]
In my team, we've been using [this wrapper script](https://gist.github.com/akshaymankar/72e0264e74c8916a778223ac8c27ac31) to do the same thing. But it would be great if this was a fly functionality.

**Comment by jtarchie** [comment]
We like. Are only request was to add support for `watch` and `abort-build` to have consistent support for `--url`. It has been captured in this [story](https://www.pivotaltracker.com/story/show/150299898).

**Comment by vito** [comment]
I'm just gonna go ahead and merge this even though it's not quite 100% how we'd like; it has tests and a lot of people want it. I'd really appreciate a follow-up PR from anyone that wants to make all the interactions with builds accept the URL as a flag generically, though.

It could also be nice to have the target autodetected by the URL.

**Comment by dsharp-pivotal** [comment]
@vito Thanks! I think the Greenplum Toolsmiths team has it on their backlog to implement the remaining functionality if someone else doesn't get to it first.

**Pull request merged**
