### PR TITLE
Updates Readme to reflect fly sync behavior

### PR DESCRIPTION
**Pull request by bebepeng**
I was surprised when I tried to update my version of fly. I did not realize that Concourse specifies the version of fly it needs.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bebepeng Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/fly&pullRequestId=136) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by bebepeng** [comment]
The click here link is giving me an error

**Comment by vito** [comment]
The CLA bot should be fixed now.

I find the placement of the note to be confusing; if they've just downloaded it from the web UI, they won't need to `sync`. Maybe it could be mentioned as an alternative to re-downloading from the UI, when you already have a `fly` locally?

**Comment by pivotal-issuemaster** [comment]
@bebepeng Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/fly&pullRequestId=136)!

**Comment by bebepeng** [comment]
The intent of the note was to highlight that you cannot just upgrade fly.
An upgrade of fly should always correlate with an upgrade of concourse.   I
think the point about an UI alternative is valid though. @vito

**Comment by vito** [comment]
thanks!

**Pull request merged**
